<#
.SYNOPSIS
    Repository Guardian - deterministic validation for focoit-ai-digest.

.DESCRIPTION
    Re-scoped from the AI Engineering Playbook's guardian for a PRODUCT / static-site
    repo (adopt-in-a-project.md: "copy the mechanism, rewrite the rules"). This repo
    ships a GitHub Pages site (docs/) generated by an agentic gh-aw workflow, so the
    playbook's "reject product/customer code" rules do NOT apply here.

    Kept (the checks a static-site repo actually needs):
      Secret detection      (Critical - blocks)   secrets never belong in the tree;
                                                   the ANTHROPIC_API_KEY lives in repo
                                                   Actions secrets, not in files.
      Repository structure  (High     - warns)     relaxed allow-list for this repo.
      Forbidden binaries    (Critical - blocks)    no .exe/.dll/.iso/weights/etc.
      Large files (> 10 MB) (High     - blocks)    keep the Pages site lean.

    Dropped (playbook-doc-specific, inapplicable to a product repo):
      - Review-required source extensions (.html/.js/.json are first-class here).
      - GOV-007 documentation metadata (Title/Purpose/Status) + kebab-case filenames
        (the playbook doc schema; would flag README, the site, and the gh-aw .md source).

.PARAMETER All
    Scan every tracked file instead of only the staged change set.

.PARAMETER Strict
    Treat warnings as blocking failures (non-zero exit). Used by CI.

.OUTPUTS
    Exit code 0 = clean (or warnings only, non-strict), 1 = blocking findings.
#>
[CmdletBinding()]
param(
    [switch]$All,
    [switch]$Strict
)

$ErrorActionPreference = 'Stop'

# --- Rule configuration (this repo's shape) ---------------------------------
$AllowedRoots = @(
    'docs','scripts','policies','roadmap','.github','.githooks','.claude'
)
$ReservedRootFiles = @(
    'README.md','LICENSE','LICENSE.md','CONTRIBUTING.md','SECURITY.md',
    'CLAUDE.md','CNAME','.gitignore','.gitattributes'
)
$ForbiddenExt = @('.exe','.dll','.iso','.gguf','.bin')
# Text extensions eligible for the fallback secret scan (includes the static-site types).
$TextExt = @('.md','.yml','.yaml','.json','.ps1','.sh','.py','.txt','.html','.css','.js','.cfg','.ini','')
$MaxBytes = 10MB

# Structured-secret patterns only (no bare keywords, so docs that MENTION
# "API keys" do not false-positive).
$SecretPatterns = @(
    @{ Name = 'Anthropic API key';   Regex = 'sk-ant-[A-Za-z0-9_\-]{20,}' },
    @{ Name = 'OpenAI project key';  Regex = 'sk-proj-[A-Za-z0-9_\-]{20,}' },
    @{ Name = 'AWS access key id';   Regex = 'AKIA[0-9A-Z]{16}' },
    @{ Name = 'GitHub token';        Regex = 'gh[pousr]_[A-Za-z0-9]{36,}' },
    @{ Name = 'Slack token';         Regex = 'xox[baprs]-[A-Za-z0-9-]{10,}' },
    @{ Name = 'Private key block';   Regex = '-----BEGIN [A-Z ]*PRIVATE KEY-----' },
    @{ Name = 'Azure storage key';   Regex = 'AccountKey=[A-Za-z0-9+/=]{30,}' },
    @{ Name = 'Google API key';      Regex = 'AIza[0-9A-Za-z_\-]{35}' }
)

# --- Findings ---------------------------------------------------------------
$findings = [System.Collections.Generic.List[object]]::new()
function Add-Finding {
    param([string]$Severity, [bool]$Block, [string]$Rule, [string]$File, [string]$Message)
    $findings.Add([pscustomobject]@{
        Severity = $Severity; Block = $Block; Rule = $Rule; File = $File; Message = $Message
    })
}

# --- Resolve repo + file set ------------------------------------------------
$repoRoot = (& git rev-parse --show-toplevel 2>$null)
if (-not $repoRoot) { Write-Error 'Not inside a git repository.'; exit 2 }
Set-Location $repoRoot

if ($All) {
    $files = & git ls-files
} else {
    $files = & git diff --cached --name-only --diff-filter=ACM
}
$files = $files | Where-Object { $_ -and $_.Trim() }

if (-not $files) {
    Write-Host '[guardian] No files to validate.' -ForegroundColor DarkGray
    exit 0
}

# --- gitleaks availability (preferred secret tooling) -----------------------
$gitleaks = Get-Command gitleaks -ErrorAction SilentlyContinue

foreach ($file in $files) {
    $ext  = [System.IO.Path]::GetExtension($file).ToLowerInvariant()
    $name = [System.IO.Path]::GetFileName($file)
    $root = ($file -split '/')[0]
    $isRootFile = ($file -notmatch '/')

    # Structure: allowed roots / reserved root files
    if (-not $isRootFile) {
        if ($AllowedRoots -notcontains $root) {
            Add-Finding 'High' $false 'STRUCT' $file "Unexpected root folder '$root/' - review before accepting."
        }
    } elseif ($ReservedRootFiles -notcontains $name) {
        Add-Finding 'High' $false 'STRUCT' $file "Unexpected root file '$name' - review before accepting."
    }

    # Forbidden binary types
    if ($ForbiddenExt -contains $ext) {
        Add-Finding 'Critical' $true 'BINARY' $file "Forbidden file type '$ext' (binaries/weights must not be committed)."
    }

    if (-not (Test-Path -LiteralPath $file)) { continue }
    # -Force: on Linux, dotfiles (.gitattributes, .githooks/*) are hidden and
    # Get-Item skips hidden items without it (works on Windows either way).
    $item = Get-Item -LiteralPath $file -Force

    # Large files
    if ($item.Length -gt $MaxBytes) {
        $mb = [math]::Round($item.Length / 1MB, 1)
        Add-Finding 'High' $true 'SIZE' $file "File is ${mb} MB, over the 10 MB limit (needs explicit approval)."
    }

    # Fallback secret scan on reasonably sized text files (only when gitleaks is absent)
    $isText = ($TextExt -contains $ext)
    if ($isText -and $item.Length -le $MaxBytes -and -not $gitleaks) {
        $content = Get-Content -LiteralPath $file -Raw -Force -ErrorAction SilentlyContinue
        if ($content) {
            foreach ($p in $SecretPatterns) {
                if ($content -match $p.Regex) {
                    Add-Finding 'Critical' $true 'SECRET' $file "Possible $($p.Name) detected - remove before committing."
                }
            }
        }
    }
}

# --- Secret scan via gitleaks (preferred) -----------------------------------
# Uses the modern `gitleaks git` verbs (8.19+).
if ($gitleaks) {
    $glArgs = if ($All) { @('git','--no-banner','--redact') }
              else       { @('git','--staged','--no-banner','--redact') }
    & gitleaks @glArgs 2>$null | Out-Null
    if ($LASTEXITCODE -ne 0) {
        Add-Finding 'Critical' $true 'SECRET' '(gitleaks)' 'gitleaks reported potential secrets - run "gitleaks git --verbose" for detail.'
    }
} else {
    Write-Host '[guardian] gitleaks not found - using built-in pattern fallback (install gitleaks for full coverage).' -ForegroundColor DarkYellow
}

# --- Report -----------------------------------------------------------------
$blocking = @($findings | Where-Object { $_.Block -or ($Strict -and $_.Severity -ne 'Low') })
$warnings = @($findings | Where-Object { $_ -notin $blocking })

if ($findings.Count -eq 0) {
    Write-Host '[guardian] PASS - no governance issues found.' -ForegroundColor Green
    exit 0
}

Write-Host ''
Write-Host 'Repository Guardian - validation report' -ForegroundColor Cyan
Write-Host '========================================'
foreach ($f in ($findings | Sort-Object @{E={switch($_.Severity){'Critical'{0}'High'{1}'Medium'{2}'Low'{3}}}})) {
    $tag   = if ($f.Block) { 'BLOCK' } else { 'warn ' }
    $color = if ($f.Block) { 'Red' } else { 'Yellow' }
    Write-Host ("  [{0}] {1,-8} {2}" -f $tag, $f.Rule, $f.File) -ForegroundColor $color
    Write-Host ("           {0}" -f $f.Message) -ForegroundColor DarkGray
}
Write-Host '----------------------------------------'
Write-Host ("  {0} blocking, {1} warning(s)" -f $blocking.Count, $warnings.Count)

if ($blocking.Count -gt 0) {
    Write-Host '[guardian] FAIL - resolve blocking findings, or bypass with: git commit --no-verify' -ForegroundColor Red
    exit 1
}

Write-Host '[guardian] PASS with warnings.' -ForegroundColor Green
exit 0
